@baseUrl = http://localhost:3003
@blogRoute = /api/blogs
@usersRoute = /api/users
GET {{baseUrl}} HTTP/1.1
###
GET {{baseUrl}}{{blogRoute}} HTTP/1.1
###
POST {{baseUrl}}{{blogRoute}} HTTP/1.1
Content-Type: application/json

{
    "title": "Second title",
    # "author": "unknown",
    "url": "lagjko/dig",
    "likes": "2"
}

###
DELETE {{baseUrl}}{{blogRoute}}/61310577b09149ff58cca9c HTTP/1.1

###
PUT {{baseUrl}}{{blogRoute}}/61323586556d180961f222a3 HTTP/1.1
Content-Type: application/json

{
    "title": "Second title",
    "author": "unknown",
    "url": "lagjko/dig",
    "likes": "3"
}

### 
GET {{baseUrl}}{{usersRoute}} HTTP/1.1
Content-Type: application/json
###
POST {{baseUrl}}{{usersRoute}} HTTP/1.1
Content-Type:  application/json

{
    "username" : "Jaon114",
    "name" : "Jane",
    "password" : "password1234"
}